template-file-path: ./iam-lab-cloudformation.yaml
parameters:
  - parameter-key: EnvironmentName
    parameter-value: iam-lab
tags:
  - key: Lab
    value: IAM-Automation
  - key: ManagedBy
    value: GitSync